platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    setup_ci if ENV['CI']

    # Fetch the App Store Connect API key from environment variables
    api_key = app_store_connect_api_key(
      key_id: "4H4SNV6S4X",
      issuer_id: "5a79245e-a76f-45fc-b6d7-c1282c9063c6",
      key_filepath: "AuthKey_4H4SNV6S4X.p8"
    )

    
    # Ensure profiles and certificates are managed
    match(
      type: "appstore",
      app_identifier: "org.reactjs.native.example.GetStart",
      api_key: api_key,
      readonly: true
    )

    increment_build_number(build_number: 2)

    build_app(
      workspace: "GetStart.xcworkspace",
      scheme: "GetStart",
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {
          "org.reactjs.native.example.GetStart" => "match AppStore org.reactjs.native.example.GetStart"
        }
      },
      xcargs: "-allowProvisioningUpdates"
    )

    pilot(
      api_key: api_key,
      skip_waiting_for_build_processing: true
    )
  end
end
